### PR TITLE
Derek furst/identify paired datasets

### PR DESCRIPTION
**Pull request by DerekFurstPitt**
Implemented endpoint `datasets/paired-dataset` which takes a dataset id (hubmap_id or uuid) and a target data type, and will search for paired datasets of that data_type who a first sample ancestor with the given dataset. Optionally, search depth query
parameter sets the max number of generations beneath the sample ancestor to search for the paired dataset. Added accompanying function in app_neo4j_queries.

### CODE REVIEW

**Comment by DerekFurstPitt** [comment]
Tagging @SFD5311 as an additional reviewer to make sure that this has the desired functionality. 

Basically the endpoint accepts the uuid or hubmap id of the dataset we want to find paired datasets for in the url path. There are 2 query parameters, one optional, one mandatory. The mandatory one is the data_type we're searching for. The optional one is "search depth" which determines how many generations down to search. 

It returns a list with the uuid's of all (if any) matching datasets of the specified data_type that share the nearest sample ancestor with the dataset who's id is provided by the user. 

If this is not the functionality you're looking for or if there's any changes you'd make, let me know and I'll make modifications

**Review by SFD5311 — APPROVED** [review]
Looks great.  Thanks!

**Review by shirey — APPROVED** [review]
Looks good

**Comment by shirey** [comment]
Approved.

**Pull request merged**
